/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(band_spec_vector.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(2925da157222ea0218deaf76e9d0f68a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/sparsdr/band_spec_vector.h>
// pydoc.h is automatically generated in the build directory
#include <band_spec_vector_pydoc.h>

// PYBIND11_MAKE_OPAQUE(std::vector<::gr::sparsdr::band_spec>)

void bind_band_spec_vector(py::module& m)
{
    using band_spec_vector = ::gr::sparsdr::band_spec_vector;

    py::class_<band_spec_vector, std::shared_ptr<band_spec_vector>>(m, "band_spec_vector", D(band_spec_vector))
        .def(py::init())
        .def("push_back", &band_spec_vector::push_back, D(band_spec_vector, push_back))
        .def("get_values", &band_spec_vector::get_values, D(band_spec_vector, get_values))
        ;

}
