/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(band_spec.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b149cd7356916b08af6864611851c3b8)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/sparsdr/band_spec.h>
// pydoc.h is automatically generated in the build directory
#include <band_spec_pydoc.h>

void bind_band_spec(py::module& m)
{
    using band_spec = ::gr::sparsdr::band_spec;

    py::class_<band_spec, std::shared_ptr<band_spec>>(m, "band_spec", D(band_spec))

        .def(py::init<float, int16_t>(),
           py::arg("freq") = 0.0,
           py::arg("bins") = 0,
           D(band_spec, 0)
        )
        .def("frequency", &band_spec::frequency, D(band_spec, frequency))

        .def("bins", &band_spec::bins, D(band_spec, bins))
        ;
}








