/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(simple_combined_pluto_receiver.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9705f29dc5c2ac46583a9481baa42254)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/sparsdr/simple_combined_pluto_receiver.h>
// pydoc.h is automatically generated in the build directory
#include <simple_combined_pluto_receiver_pydoc.h>

void bind_simple_combined_pluto_receiver(py::module& m)
{
    using simple_combined_pluto_receiver    = ::gr::sparsdr::simple_combined_pluto_receiver;

    py::class_<simple_combined_pluto_receiver, gr::hier_block2,
        std::shared_ptr<simple_combined_pluto_receiver>>(m, "simple_combined_pluto_receiver", D(simple_combined_pluto_receiver))

        .def(py::init(&simple_combined_pluto_receiver::make),
           py::arg("uri"),
           py::arg("buffer_size"),
           py::arg("center_frequency"),
           py::arg("bands"),
           py::arg("threshold"),
           py::arg("reconstruct_path") = "sparsdr_reconstruct",
           py::arg("zero_gaps") = false,
           py::arg("skip_bin_config") = false,
           D(simple_combined_pluto_receiver,make)
        )
        
        .def("set_gain",&simple_combined_pluto_receiver::set_gain,       
            py::arg("gain"),
            D(simple_combined_pluto_receiver,set_gain)
        )

        .def("set_gain_control_mode",&simple_combined_pluto_receiver::set_gain_control_mode,       
            py::arg("mode"),
            D(simple_combined_pluto_receiver,set_gain_control_mode)
        )
        
        .def("set_shift_amount",&simple_combined_pluto_receiver::set_shift_amount,       
            py::arg("scaling"),
            D(simple_combined_pluto_receiver,set_shift_amount)
        )
        ;
}
